### ISSUE TITLE
IDE Error Report

### ISSUE THREAD

**Issue by Xirado** [marhali/easy-i18n#132]
# Additional information
null
# Exception trace
An error occurred while processing translation files. 
Config: SINGLE => YAML (*.yml) 
Path: C:\Users\Marce\Documents\Bean\src\main\resources\i18n\locales 
Please check examples at https://github.com/marhali/easy-i18n before reporting an issue!
```
java.io.IOException: TranslationFile{virtualFile=file://C:/Users/Marce/Documents/Bean/src/main/resources/i18n/locales/en_US.yml, locale='en_US', namespace='null'}

while parsing a block mapping
 in 'reader', line 2, column 5:
        unknown_error_occurred: 'We're s ... 
        ^
expected <block end>, but found '<scalar>'
 in 'reader', line 2, column 33:
        unknown_error_occurred: 'We're sorry, but something weird ha ... 
                                    ^

	at de.marhali.easyi18n.io.IOHandler.read(IOHandler.java:69)
	at de.marhali.easyi18n.DataStore.lambda$loadFromPersistenceLayer$0(DataStore.java:57)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:907)
	at de.marhali.easyi18n.DataStore.loadFromPersistenceLayer(DataStore.java:55)
	at de.marhali.easyi18n.InstanceManager.lambda$new$1(InstanceManager.java:41)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:215)
	at com.intellij.openapi.application.TransactionGuardImpl.access$100(TransactionGuardImpl.java:22)
	at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:197)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:873)
	at com.intellij.openapi.application.impl.ApplicationImpl$3.run(ApplicationImpl.java:511)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:69)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:112)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:42)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:898)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:439)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:803)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:438)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:106)
	at com.intellij.ide.IdeEventQueue.performActivity(IdeEventQueue.java:604)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:436)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:873)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:484)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
Caused by: while parsing a block mapping
 in 'reader', line 2, column 5:
        unknown_error_occurred: 'We're s ... 
        ^
expected <block end>, but found '<scalar>'
 in 'reader', line 2, column 33:
        unknown_error_occurred: 'We're sorry, but something weird ha ... 
                                    ^

	at org.yaml.snakeyaml.parser.ParserImpl$ParseBlockMappingKey.produce(ParserImpl.java:644)
	at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:166)
	at org.yaml.snakeyaml.comments.CommentEventsCollector$1.peek(CommentEventsCollector.java:59)
	at org.yaml.snakeyaml.comments.CommentEventsCollector$1.peek(CommentEventsCollector.java:45)
	at org.yaml.snakeyaml.comments.CommentEventsCollector.collectEvents(CommentEventsCollector.java:140)
	at org.yaml.snakeyaml.comments.CommentEventsCollector.collectEvents(CommentEventsCollector.java:119)
	at org.yaml.snakeyaml.composer.Composer.composeScalarNode(Composer.java:214)
	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:184)
	at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:314)
	at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:305)
	at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:286)
	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:188)
	at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:314)
	at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:305)
	at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:286)
	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:188)
	at org.yaml.snakeyaml.composer.Composer.getNode(Composer.java:115)
	at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:142)
	at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:151)
	at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:491)
	at org.yaml.snakeyaml.Yaml.loadAs(Yaml.java:456)
	at thito.nodeflow.config.Section.parseToMap(Section.java:58)
	at de.marhali.easyi18n.io.parser.yaml.YamlParserStrategy.read(YamlParserStrategy.java:37)
	at de.marhali.easyi18n.io.IOHandler.read(IOHandler.java:67)
	... 35 more

```

**Comment by marhali** [comment]
Seems like your translation file is poorly formatted. See

> Caused by: while parsing a block mapping
 in 'reader', line 2, column 5:
        unknown_error_occurred: 'We're s ... 
        ^
expected <block end>, but found '<scalar>'
 in 'reader', line 2, column 33:
        unknown_error_occurred: 'We're sorry, but something weird ha ...

**Comment by Xirado** [comment]
> Seems like your translation file is poorly formatted. See
> 
> 
> 
> > Caused by: while parsing a block mapping
> 
>  in 'reader', line 2, column 5:
> 
>         unknown_error_occurred: 'We're s ... 
> 
>         ^
> 
> expected <block end>, but found '<scalar>'
> 
>  in 'reader', line 2, column 33:
> 
>         unknown_error_occurred: 'We're sorry, but something weird ha ... 
> 
> 
> 
> 

Oops yeah, i see it now, the single auote in "We're" closes it again
