### ISSUE TITLE
IDE Error Report (v4.1.0)

### ISSUE THREAD

**Issue by AlexNek** [marhali/easy-i18n#148]
# Additional information no translation directory at all --> no exception expected
/
# Exception trace
An error occurred while processing translation files. 
Config: SINGLE => JSON (*.*) 
Path: Y:\user_alex_new\Angular\tracker-mobile\src\assets 
Please check examples at https://github.com/marhali/easy-i18n before reporting an issue!
```
java.io.IOException: TranslationFile{virtualFile=file://Y:/user_alex_new/Angular/tracker-mobile/src/assets/shapes.svg, locale='shapes', namespace='null'}

Expected a com.google.gson.JsonObject but was com.google.gson.JsonPrimitive
	at de.marhali.easyi18n.io.IOHandler.read(IOHandler.java:77)
	at de.marhali.easyi18n.DataStore.lambda$loadFromPersistenceLayer$0(DataStore.java:57)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:907)
	at de.marhali.easyi18n.DataStore.loadFromPersistenceLayer(DataStore.java:55)
	at de.marhali.easyi18n.InstanceManager.lambda$new$1(InstanceManager.java:46)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:215)
	at com.intellij.openapi.application.TransactionGuardImpl.access$100(TransactionGuardImpl.java:22)
	at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:197)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:873)
	at com.intellij.openapi.application.impl.ApplicationImpl$3.run(ApplicationImpl.java:511)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:69)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:112)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:42)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:898)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:439)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:803)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:438)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:106)
	at com.intellij.ide.IdeEventQueue.performActivity(IdeEventQueue.java:604)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:436)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:873)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:484)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
Caused by: com.google.gson.JsonSyntaxException: Expected a com.google.gson.JsonObject but was com.google.gson.JsonPrimitive
	at com.google.gson.internal.bind.TypeAdapters$33$1.read(TypeAdapters.java:869)
	at com.google.gson.Gson.fromJson(Gson.java:963)
	at com.google.gson.Gson.fromJson(Gson.java:901)
	at de.marhali.easyi18n.io.parser.json.JsonParserStrategy.read(JsonParserStrategy.java:39)
	at de.marhali.easyi18n.io.IOHandler.read(IOHandler.java:75)
	... 35 more

```

**Comment by marhali** [comment]
Can you please share a screenshot from the plugin's configuration page?

**Comment by AlexNek** [comment]
![2022-06-30_21-39-15](https://user-images.githubusercontent.com/2191467/176763428-fa3c8383-4d75-4b59-8378-2d08a76caf71.png)
In this directory no json files, svg only

**Comment by marhali** [comment]
If this is the directory for your translation files I would suggest to change the filter to `*.json` in the <kbd>File structure</kbd> section. This should avoid that svg will be parsed as translation files by the plugin.

**Comment by AlexNek** [comment]
thanks, I already did it. I want to tell that after the last update there a lot of different exceptions which I can not sent - too long message.
I don't need translation at all for this project so I need to set something. I think we need some better solution for projects without translation

**Comment by marhali** [comment]
Just clear the "Locales Directory" path and save it. The plugin should work now as if there is no configuration.

**Comment by AlexNek** [comment]
It doesn't help - I have annoying message from Rider
![2022-07-01_12-51-45](https://user-images.githubusercontent.com/2191467/176881043-b6257825-f609-42b8-96ba-740baee35565.png)

**Comment by marhali** [comment]
Just close the notification or disable notifications by configuring <kbd>Easy I18n Notification Group</kbd>.

**Comment by AlexNek** [comment]
>Just close the notification
Every time after project opening?
>disable notifications by configuring 
But I want to have another notifications

**Comment by marhali** [comment]
> It doesn't help - I have annoying message from Rider ![2022-07-01_12-51-45](https://user-images.githubusercontent.com/2191467/176881043-b6257825-f609-42b8-96ba-740baee35565.png)

Removed that warning with upcoming release.
