### ISSUE TITLE
IDE Error Report (v4.2.3)

### ISSUE THREAD

**Issue by copostic** [marhali/easy-i18n#185]
# Additional information
/
# Exception trace
An error occurred while processing translation files. 
Config: SINGLE => JSON (*.*) 
Path: C:\Users\XXXXX\WebstormProjects\landing\locales 
Please check examples at https://github.com/marhali/easy-i18n before reporting an issue!
```
java.io.IOException: TranslationFile{virtualFile=file://C:/Users/XXXXX/WebstormProjects/landing/locales/en.json, locale='en', namespace='null'}

com.google.gson.stream.MalformedJsonException: Unterminated object at line 1 column 79 path $.description
	at de.marhali.easyi18n.io.IOHandler.write(IOHandler.java:128)
	at de.marhali.easyi18n.DataStore.lambda$saveToPersistenceLayer$1(DataStore.java:81)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:1023)
	at de.marhali.easyi18n.DataStore.saveToPersistenceLayer(DataStore.java:79)
	at de.marhali.easyi18n.InstanceManager.processUpdate(InstanceManager.java:88)
	at de.marhali.easyi18n.dialog.TranslationDialog.showAndHandle(TranslationDialog.java:102)
	at de.marhali.easyi18n.dialog.EditDialog.showAndHandle(EditDialog.java:21)
	at de.marhali.easyi18n.assistance.reference.PsiKeyReference$TranslationReference.navigate(PsiKeyReference.java:52)
	at com.intellij.codeInsight.navigation.actions.IdeKt.navigateRequest(ide.kt:64)
	at com.intellij.codeInsight.navigation.actions.GotoDeclarationOnlyHandler2.gotoDeclaration$intellij_platform_lang_impl(GotoDeclarationOnlyHandler2.kt:79)
	at com.intellij.codeInsight.navigation.actions.GotoDeclarationOrUsageHandler2.invoke(GotoDeclarationOrUsageHandler2.kt:67)
	at com.intellij.codeInsight.actions.CodeInsightAction.lambda$actionPerformedImpl$0(CodeInsightAction.java:68)
	at com.intellij.codeInsight.actions.CodeInsightAction.lambda$actionPerformedImpl$1(CodeInsightAction.java:74)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:219)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:174)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:155)
	at com.intellij.codeInsight.actions.CodeInsightAction.actionPerformedImpl(CodeInsightAction.java:65)
	at com.intellij.codeInsight.actions.CodeInsightAction.actionPerformed(CodeInsightAction.java:40)
	at com.intellij.codeInsight.navigation.actions.GotoDeclarationAction.actionPerformed(GotoDeclarationAction.java:70)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.doPerformActionOrShowPopup(ActionUtil.java:315)
	at com.intellij.openapi.keymap.impl.ActionProcessor.performAction(ActionProcessor.java:47)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.lambda$doPerformActionInner$9(IdeKeyEventDispatcher.java:717)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:105)
	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:94)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.lambda$doPerformActionInner$10(IdeKeyEventDispatcher.java:717)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareWithCallbacks(ActionUtil.java:337)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.doPerformActionInner(IdeKeyEventDispatcher.java:714)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:658)
	at com.intellij.openapi.keymap.impl.IdeMouseEventDispatcher.processEvent(IdeMouseEventDispatcher.java:271)
	at com.intellij.openapi.keymap.impl.IdeMouseEventDispatcher.dispatchMouseEvent(IdeMouseEventDispatcher.java:255)
	at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.java:839)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:763)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:450)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:791)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:449)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:113)
	at com.intellij.ide.IdeEventQueue.performActivity(IdeEventQueue.java:624)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:447)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:881)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:493)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
Caused by: com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Unterminated object at line 1 column 79 path $.description
	at com.google.gson.Gson.fromJson(Gson.java:1006)
	at com.google.gson.Gson.fromJson(Gson.java:956)
	at com.google.gson.Gson.fromJson(Gson.java:905)
	at com.google.gson.Gson.fromJson(Gson.java:876)
	at de.marhali.easyi18n.io.parser.json.JsonArrayMapper.lambda$write$1(JsonArrayMapper.java:26)
	at de.marhali.easyi18n.io.parser.ArrayMapper.write(ArrayMapper.java:54)
	at de.marhali.easyi18n.io.parser.json.JsonArrayMapper.write(JsonArrayMapper.java:24)
	at de.marhali.easyi18n.io.parser.json.JsonMapper.write(JsonMapper.java:63)
	at de.marhali.easyi18n.io.parser.json.JsonMapper.write(JsonMapper.java:53)
	at de.marhali.easyi18n.io.parser.json.JsonMapper.write(JsonMapper.java:53)
	at de.marhali.easyi18n.io.parser.json.JsonParserStrategy.write(JsonParserStrategy.java:51)
	at de.marhali.easyi18n.io.IOHandler.write(IOHandler.java:102)
	... 45 more
Caused by: com.google.gson.stream.MalformedJsonException: Unterminated object at line 1 column 79 path $.description
	at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1597)
	at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:491)
	at com.google.gson.stream.JsonReader.hasNext(JsonReader.java:414)
	at com.google.gson.internal.bind.TypeAdapters$28.read(TypeAdapters.java:725)
	at com.google.gson.internal.bind.TypeAdapters$28.read(TypeAdapters.java:697)
	at com.google.gson.internal.bind.TypeAdapters$34$1.read(TypeAdapters.java:917)
	at com.google.gson.Gson.fromJson(Gson.java:991)
	... 56 more

```

**Comment by marhali** [comment]
> java.io.IOException: TranslationFile{virtualFile=file://C:/Users/XXXXX/WebstormProjects/landing/locales/en.json, locale='en', namespace='null'}

> com.google.gson.stream.MalformedJsonException: Unterminated object at line 1 column 79 path $.description

Please check this file at the specified location.
