### ISSUE TITLE
IDE Error Report (v4.2.3)

### ISSUE THREAD

**Issue by xiaoyu-a** [marhali/easy-i18n#192]
# Additional information
/
# Exception trace
An error occurred while processing translation files. 
Config: MODULARIZED_LOCALE => JSON (*.*) 
Path: /Users/xiaoyu/illacloud.com/public/locales 
Please check examples at https://github.com/marhali/easy-i18n before reporting an issue!
```
java.io.IOException: TranslationFile{virtualFile=file:///Users/xiaoyu/illacloud.com/public/locales/zh-CN/careers.json, locale='zh-CN', namespace='[careers]'}

com.google.gson.stream.MalformedJsonException: Expected name at line 53 column 6 path $.recruiting.Golang.requirements
	at de.marhali.easyi18n.io.IOHandler.read(IOHandler.java:77)
	at de.marhali.easyi18n.DataStore.lambda$loadFromPersistenceLayer$0(DataStore.java:57)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:907)
	at de.marhali.easyi18n.DataStore.loadFromPersistenceLayer(DataStore.java:55)
	at de.marhali.easyi18n.InstanceManager.lambda$new$1(InstanceManager.java:46)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:215)
	at com.intellij.openapi.application.TransactionGuardImpl.access$100(TransactionGuardImpl.java:22)
	at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:197)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:873)
	at com.intellij.openapi.application.impl.ApplicationImpl$3.run(ApplicationImpl.java:511)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:69)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:112)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:42)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:898)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:439)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:803)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:438)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:106)
	at com.intellij.ide.IdeEventQueue.performActivity(IdeEventQueue.java:604)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:436)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:873)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:484)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
Caused by: com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Expected name at line 53 column 6 path $.recruiting.Golang.requirements
	at com.google.gson.Gson.fromJson(Gson.java:978)
	at com.google.gson.Gson.fromJson(Gson.java:901)
	at de.marhali.easyi18n.io.parser.json.JsonParserStrategy.read(JsonParserStrategy.java:39)
	at de.marhali.easyi18n.io.IOHandler.read(IOHandler.java:75)
	... 35 more
Caused by: com.google.gson.stream.MalformedJsonException: Expected name at line 53 column 6 path $.recruiting.Golang.requirements
	at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1562)
	at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:504)
	at com.google.gson.stream.JsonReader.hasNext(JsonReader.java:413)
	at com.google.gson.internal.bind.TypeAdapters$27.read(TypeAdapters.java:683)
	at com.google.gson.internal.bind.TypeAdapters$27.read(TypeAdapters.java:684)
	at com.google.gson.internal.bind.TypeAdapters$27.read(TypeAdapters.java:684)
	at com.google.gson.internal.bind.TypeAdapters$27.read(TypeAdapters.java:655)
	at com.google.gson.internal.bind.TypeAdapters$33$1.read(TypeAdapters.java:866)
	at com.google.gson.Gson.fromJson(Gson.java:963)
	... 38 more

```

**Comment by marhali** [comment]
> Caused by: com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Expected name at line 53 column 6 path $.recruiting.Golang.requirements
