### ISSUE TITLE
IDE Error Report (v4.4.1)

### ISSUE THREAD

**Issue by flynn0909** [marhali/easy-i18n#247]
# Additional information
/
# Exception trace
An error occurred while processing translation files. 
Config: MODULARIZED_LOCALE => JSON (*.*) 
Path: /Users/dongyeongchon/Desktop/acon3d/public/locales 
Please check examples at https://github.com/marhali/easy-i18n before reporting an issue!
```
java.io.IOException: TranslationFile{virtualFile=file:///Users/dongyeongchon/Desktop/acon3d/public/locales/en/common.json, locale='en', namespace='[common]'}

com.google.gson.stream.MalformedJsonException: Unterminated object at line 1 column 1159 path $.project
	at de.marhali.easyi18n.io.IOHandler.write(IOHandler.java:134)
	at de.marhali.easyi18n.DataStore.lambda$saveToPersistenceLayer$1(DataStore.java:78)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:980)
	at de.marhali.easyi18n.DataStore.saveToPersistenceLayer(DataStore.java:76)
	at de.marhali.easyi18n.InstanceManager.processUpdate(InstanceManager.java:89)
	at de.marhali.easyi18n.dialog.TranslationDialog.showAndHandle(TranslationDialog.java:99)
	at de.marhali.easyi18n.dialog.EditDialog.showAndHandle(EditDialog.java:20)
	at de.marhali.easyi18n.assistance.reference.PsiKeyReference$TranslationReference.navigate(PsiKeyReference.java:52)
	at com.intellij.codeInsight.navigation.actions.IdeKt.navigateRequest(ide.kt:74)
	at com.intellij.codeInsight.navigation.actions.GotoDeclarationOnlyHandler2.gotoDeclaration$intellij_platform_lang_impl(GotoDeclarationOnlyHandler2.kt:77)
	at com.intellij.codeInsight.navigation.actions.GotoDeclarationOrUsageHandler2.invoke(GotoDeclarationOrUsageHandler2.kt:65)
	at com.intellij.codeInsight.actions.CodeInsightAction.lambda$actionPerformedImpl$0(CodeInsightAction.java:68)
	at com.intellij.codeInsight.actions.CodeInsightAction.lambda$actionPerformedImpl$1(CodeInsightAction.java:74)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:219)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:174)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:155)
	at com.intellij.codeInsight.actions.CodeInsightAction.actionPerformedImpl(CodeInsightAction.java:65)
	at com.intellij.codeInsight.actions.CodeInsightAction.actionPerformed(CodeInsightAction.java:40)
	at com.intellij.codeInsight.navigation.actions.GotoDeclarationAction.actionPerformed(GotoDeclarationAction.java:69)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.doPerformActionOrShowPopup(ActionUtil.java:327)
	at com.intellij.openapi.keymap.impl.ActionProcessor.performAction(ActionProcessor.java:47)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.lambda$doPerformActionInner$9(IdeKeyEventDispatcher.java:706)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:105)
	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:94)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.lambda$doPerformActionInner$10(IdeKeyEventDispatcher.java:706)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareWithCallbacks(ActionUtil.java:350)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.doPerformActionInner(IdeKeyEventDispatcher.java:703)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:647)
	at com.intellij.openapi.keymap.impl.IdeMouseEventDispatcher.processEvent(IdeMouseEventDispatcher.java:269)
	at com.intellij.openapi.keymap.impl.IdeMouseEventDispatcher.dispatchMouseEvent(IdeMouseEventDispatcher.java:253)
	at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.java:830)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:753)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$5(IdeEventQueue.java:437)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:787)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:436)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:113)
	at com.intellij.ide.IdeEventQueue.performActivity(IdeEventQueue.java:615)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:434)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:838)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:480)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
Caused by: com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Unterminated object at line 1 column 1159 path $.project
	at com.google.gson.Gson.fromJson(Gson.java:1073)
	at com.google.gson.Gson.fromJson(Gson.java:1016)
	at com.google.gson.Gson.fromJson(Gson.java:959)
	at com.google.gson.Gson.fromJson(Gson.java:927)
	at de.marhali.easyi18n.io.parser.json.JsonArrayMapper.lambda$write$1(JsonArrayMapper.java:26)
	at de.marhali.easyi18n.io.parser.ArrayMapper.write(ArrayMapper.java:54)
	at de.marhali.easyi18n.io.parser.json.JsonArrayMapper.write(JsonArrayMapper.java:24)
	at de.marhali.easyi18n.io.parser.json.JsonMapper.write(JsonMapper.java:63)
	at de.marhali.easyi18n.io.parser.json.JsonMapper.write(JsonMapper.java:53)
	at de.marhali.easyi18n.io.parser.json.JsonMapper.write(JsonMapper.java:53)
	at de.marhali.easyi18n.io.parser.json.JsonParserStrategy.write(JsonParserStrategy.java:60)
	at de.marhali.easyi18n.io.IOHandler.write(IOHandler.java:108)
	... 45 more
Caused by: com.google.gson.stream.MalformedJsonException: Unterminated object at line 1 column 1159 path $.project
	at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1607)
	at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:501)
	at com.google.gson.stream.JsonReader.hasNext(JsonReader.java:424)
	at com.google.gson.internal.bind.TypeAdapters$28.read(TypeAdapters.java:752)
	at com.google.gson.internal.bind.TypeAdapters$28.read(TypeAdapters.java:698)
	at com.google.gson.internal.bind.TypeAdapters$34$1.read(TypeAdapters.java:979)
	at com.google.gson.Gson.fromJson(Gson.java:1058)
	... 56 more

```

**Comment by marhali** [comment]
> java.io.IOException: TranslationFile{virtualFile=file:///Users/dongyeongchon/Desktop/acon3d/public/locales/en/common.json, locale='en', namespace='[common]'}
> com.google.gson.stream.MalformedJsonException: Unterminated object at line 1 column 1159 path $.project

Please check your translation file. The exception states that there is an malformed json object.
If not,  could you please provide an example and the steps to reproduce the error.
