### ISSUE TITLE
Version 4.4.1 seems to be incompatible with WebStorm 2023.2

### ISSUE THREAD

**Issue by mirec75** [marhali/easy-i18n#296]
do you expect a solution to the following problem soon, or shall I downgrade my WebStorm?

I have the problem in WebStorm 2023.2 with the Easy I18n 4.4.1
Build #WS-232.8660.143, built on July 21, 2023

The problem is: _Incompatible: requires IDE build 231.* or earlier_
Detail: 
Plugin 'Easy I18n' (version '4.4.1') is not compatible with the current version of the IDE, because it requires build 231.* or older but the current build is WS-232.8660.143

![image](https://github.com/marhali/easy-i18n/assets/50924731/276d0487-7e00-4c4f-8ace-88dbae8b298b)
![image](https://github.com/marhali/easy-i18n/assets/50924731/2d5ca78a-fcbd-4802-b0ec-b8beef679d81)

**Comment by frankykubo** [comment]
Same here.

**Comment by vgammieri-private** [comment]
same here!

**Comment by laubfall** [comment]
Same here: IntelliJ IDEA 2023.2 (Ultimate Edition)

**Comment by Triskae** [comment]
Same here

**Comment by Abdulrahmanelheyb** [comment]
And me too

**Comment by pilutiful** [comment]
Same here with PHPStorm 2023.2

**Comment by MiguelALopez** [comment]
Same here WebStorm 2023.2

**Comment by ningkexin** [comment]
@laubfall @MiguelALopez @Triskae @Abdulrahmanelheyb @frankykubo 
I submitted a pull request to temporarily use my packaged zip 
[easy-i18n-4.4.2.jar.zip](https://github.com/marhali/easy-i18n/files/12404210/easy-i18n-4.4.2.jar.zip)

**Comment by frankykubo** [comment]
Thats really nice @ningkexin ! 

Please, if someone is using with Vue-i18n, are able to select the vue-i18n preset in plugin settings? I cannot make it work. When I close the settings and open again, the config is lost and I have 'nothing to show' in plugin's tab all the time.

**Comment by MiguelALopez** [comment]
I have this error when I try to open the plugin tab with the zip provided

`java.lang.NullPointerException: Cannot invoke "javax.swing.JPanel.add(java.awt.Component)" because "this.containerPanel" is null
	at de.marhali.easyi18n.tabs.TreeView.<init>(TreeView.java:64)
	at de.marhali.easyi18n.service.TranslatorToolWindowFactory.createToolWindowContent(TranslatorToolWindowFactory.java:34)
	at com.intellij.openapi.wm.impl.ToolWindowImpl.createContentIfNeeded(ToolWindowImpl.kt:554)
	at com.intellij.openapi.wm.impl.ToolWindowImpl.scheduleContentInitializationIfNeeded$intellij_platform_ide_impl(ToolWindowImpl.kt:533)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.doShowWindow(ToolWindowManagerImpl.kt:1013)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.showToolWindowImpl(ToolWindowManagerImpl.kt:950)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.activateToolWindow$intellij_platform_ide_impl(ToolWindowManagerImpl.kt:657)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.activateToolWindow$intellij_platform_ide_impl$default(ToolWindowManagerImpl.kt:626)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.activated$intellij_platform_ide_impl(ToolWindowManagerImpl.kt:2048)
	at com.intellij.openapi.wm.impl.SquareAnActionButton.setSelected(SquareStripeButton.kt:172)
	at com.intellij.ui.ToggleActionButton.actionPerformed(ToggleActionButton.java:42)
	at com.intellij.openapi.actionSystem.impl.ActionButton.actionPerformed(ActionButton.java:227)
	at com.intellij.openapi.actionSystem.impl.ActionButton.lambda$performAction$2(ActionButton.java:206)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareWithCallbacks(ActionUtil.java:362)
	at com.intellij.openapi.actionSystem.impl.ActionButton.performAction(ActionButton.java:206)
	at com.intellij.openapi.actionSystem.impl.ActionButton.processMouseEvent(ActionButton.java:520)
	at java.desktop/java.awt.Component.processEvent(Component.java:6422)
	at java.desktop/java.awt.Container.processEvent(Container.java:2266)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5027)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4855)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4954)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4581)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4522)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2808)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4855)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:791)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:740)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:734)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:764)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:762)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:761)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.kt:685)
	at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.kt:633)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.kt:588)
	at com.intellij.ide.IdeEventQueue.access$_dispatchEvent(IdeEventQueue.kt:67)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:369)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:368)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:787)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:368)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:363)
	at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$1(IdeEventQueue.kt:992)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:113)
	at com.intellij.ide.IdeEventQueueKt.performActivity(IdeEventQueue.kt:992)
	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$7(IdeEventQueue.kt:363)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:861)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.kt:405)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
`

**Comment by Linknpay** [comment]
Hello,

I'm facing the same compatibility issue with Easy I18n 4.4.1 and WebStorm 2023.2.
To the Easy I18n team: this is a critical tool for many of us. Can we expect a timely update, or should we explore alternative solutions?

Thanks for addressing this promptly.

**Comment by ningkexin** [comment]
@Linknpay https://github.com/marhali/easy-i18n/issues/296#issuecomment-1687339927

**Comment by ningkexin** [comment]
@frankykubo @MiguelALopez Pls download 4.4.3 https://github.com/marhali/easy-i18n/issues/296#issuecomment-1687339927

**Comment by frankykubo** [comment]
> @frankykubo @MiguelALopez Pls download 4.4.3 [#296 (comment)](https://github.com/marhali/easy-i18n/issues/296#issuecomment-1687339927)

I can confirm this works! Cannot thank you more sir!

**Comment by MiguelALopez** [comment]
Now it works thanks @ningkexin

**Comment by frankykubo** [comment]
@ningkexin 

It's been a while, hello sir. Any chance you can make build for Webstorm 2023.3? Or maybe provide some lightweight tutorial so we can try ourselves? Thank you.

**Comment by ningkexin** [comment]
@frankykubo @marhali org.apache.commons.lang(org.apache.commons.lang3) was removed in 2023.3. I tried to add `implementation("org.apache.commons:commons-lang3:3.14.0")` and tried to build successfully. If If there are other problems, please ask the author to fix them. The following package can be used temporarily.
[easy-i18n-4.4.4.jar.zip](https://github.com/marhali/easy-i18n/files/13594459/easy-i18n-4.4.4.jar.zip)

**Comment by marhali** [comment]
Support for 2023.3 has been added in latest release ([v4.4.3](https://github.com/marhali/easy-i18n/releases/tag/v4.4.3)) and will be available after JetBrains approval. Alternatively use the manual installation as described inside the README file.

Cheers 🥂
