### ISSUE TITLE
Not working on namespaced files

### ISSUE THREAD

**Issue by AlexandreMouyen** [marhali/easy-i18n#81]
There is my files tree.

![image](https://user-images.githubusercontent.com/27637370/151666225-3f983155-2e3a-4675-bfa5-4a1d92fe0833.png)

I tryed many configs but nothing working, the plugin cannot find my files.

Can somebody help? What is the needed config?

Pretty sure I did nothing bad.

Thanks.

**Comment by marhali** [comment]
Set locales directory to **locales** directory in your screenshot.

Set file pattern to ***.json**

**Comment by AlexandreMouyen** [comment]
> Set locales directory to **locales** directory in your screenshot.
> 
> Set file pattern to ***.json**

Thanks for you answer.

I tryed many things, nothing is working.

![image](https://user-images.githubusercontent.com/27637370/151756731-a714feee-74c3-42d7-8db7-a7925a968054.png)

I don't know if it is related, but I found an error on WebStorm:

```
Could not process file en / pro with ModularizedJsonIOStrategy. Unwanted files can be ignored via Translation file wildcard matcher option.

java.lang.UnsupportedOperationException: JsonObject
	at com.google.gson.JsonElement.getAsString(JsonElement.java:179)
	at de.marhali.easyi18n.io.ArrayMapper.read(ArrayMapper.java:37)
	at de.marhali.easyi18n.io.json.JsonArrayMapper.read(JsonArrayMapper.java:13)
	at de.marhali.easyi18n.io.json.JsonMapper.read(JsonMapper.java:36)
	at de.marhali.easyi18n.io.json.JsonMapper.read(JsonMapper.java:31)
	at de.marhali.easyi18n.io.json.ModularizedJsonIOStrategy.lambda$read$0(ModularizedJsonIOStrategy.java:107)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:828)
	at de.marhali.easyi18n.io.json.ModularizedJsonIOStrategy.read(ModularizedJsonIOStrategy.java:77)
	at de.marhali.easyi18n.DataStore.loadFromPersistenceLayer(DataStore.java:74)
	at de.marhali.easyi18n.InstanceManager.lambda$new$1(InstanceManager.java:41)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:214)
	at com.intellij.openapi.application.TransactionGuardImpl.access$200(TransactionGuardImpl.java:21)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:196)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:794)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeLater$4(ApplicationImpl.java:350)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:84)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:133)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:46)
	at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:189)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:885)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:754)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:441)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:825)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:440)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:794)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:486)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Comment by marhali** [comment]
How does the <kbd>en / pro.json</kbd> file look like? Does it define at least an empty object `{}` ?

**Comment by AlexandreMouyen** [comment]
> How does the en / pro.json file look like? Does it define at least an empty object `{}` ?

I just checked on for all my locales, each file define at least an empty object.

**Comment by marhali** [comment]
> The error message indicates an array object. Can you provide an example?
Could you provide the content from file <kbd>en / pro.json</kbd>?

**Comment by AlexandreMouyen** [comment]
Oh, I understood. With i18next, you can provide an array translation.

I have this on my trad files:

```json
{
  "features": [
        {
          "text": "List your salon on the app",
          "tooltip": "You can be listed freely on PlanniPets' groomers by simply registering. That way, everyone can book an appointment in your salon."
        },
        {
          "text": "Add your services",
          "tooltip": "Add all of your services on our platform, so that customers can find out what you have to offer."
        },
        {
          "text": "Set up your opening hours",
          "tooltip": "Fill up your opening hours on the app to make it easy for your clients to know your shifts. "
        },
        {
          "text": "Customize your logo and your images",
          "tooltip": "You can customize your profile and get an edge on other groomers by uploading your brand logo and various pictures."
        }
      ]
}
```

**Comment by marhali** [comment]
Ah okay, haven't seen this form before in translation files. Currently the plugin does not support such arrays.

**Comment by marhali** [comment]
Upcoming release will add basic support to parse this edge case

**Comment by AlexandreMouyen** [comment]
Super, thanks!
